steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ucsc-menu/ucsc-menu", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ucsc-menu/ucsc-menu"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "ucsc-menu",
        "--image",
        "gcr.io/ucsc-menu/ucsc-menu",
        "--region",
        "us-west1",
      ]
images:
  - gcr.io/ucsc-menu/ucsc-menu
